trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Gradle@2
  displayName: Gradle Build
  inputs:
    workingDirectory: 'parqueaderoMicroServicio/'
    gradleWrapperFile: 'parqueaderoMicroServicio/gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    tasks: 'build'
    options: '-x test'
- task: Gradle@2
  displayName: Gradle test
  inputs:
    workingDirectory: 'parqueaderoMicroServicio/'
    gradleWrapperFile: 'parqueaderoMicroServicio/gradlew'
    tasks: 'test'
    publishJUnitResults: true
    testResultsFiles: '**/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    sonarQubeRunAnalysis: false
    spotBugsAnalysis: false